### ISSUE TITLE
Redis not working?

### ISSUE THREAD

**Issue by skylar-byte** [novnc/websockify#467] opened 2021-01-05 03:43 UTC
The token plugin for Redis appears to not be working.

```
# websockify --token-plugin TokenRedis --token-source ./token_plugins.py 5900 --
Traceback (most recent call last):
  File "/opt/web_app/venv/bin/websockify", line 8, in <module>
    sys.exit(websockify_init())
  File "/opt/web_app/venv/lib/python3.8/site-packages/websockify/websocketproxy.py", line 699, in websockify_init
    opts.token_plugin = token_plugin_cls(opts.token_source)
  File "/opt/web_app/venv/lib/python3.8/site-packages/websockify/token_plugins.py", line 142, in __init__
    self._server, self._port = src.split(":")
ValueError: not enough values to unpack (expected 2, got 1)
```

The others appear to work fine.

```
# websockify --token-plugin BaseTokenAPI --token-source ./token_plugins.py 5900 --
WebSocket server settings:
  - Listen on :5900
  - No SSL/TLS support (no cert file)
  - proxying from :5900 to targets generated by BaseTokenAPI

# websockify --token-plugin JSONTokenApi --token-source ./token_plugins.py 5900 --
WebSocket server settings:
  - Listen on :5900
  - No SSL/TLS support (no cert file)
  - proxying from :5900 to targets generated by JSONTokenApi

# websockify --token-plugin JWTTokenApi --token-source ./token_plugins.py 5900 --
WebSocket server settings:
  - Listen on :5900
  - No SSL/TLS support (no cert file)
  - proxying from :5900 to targets generated by JWTTokenApi
```

I'm running the following versions:
```
# pip list
Package          Version
---------------- -------
redis            3.5.3  
websockify       0.9.0  
```

**Comment by CendioOssman** [comment] 2021-01-05 11:07
`--token-source` should specify your redis server in a `host:port` format. Please try that and it should work better.

**Comment by skylar-byte** [comment] 2021-01-05 23:33
@CendioOssman I've tried running the function manually from the tokens file and I was able to get a response which is weird.

```
# python3 ./test2.py 
None
['10.0.0.165', '5900']
# cat test2.py 
from websockify import token_plugins

print(token_plugins.TokenRedis.__init__(token_plugins.TokenRedis, "127.0.0.1:6379"))
print(token_plugins.TokenRedis.lookup(token_plugins.TokenRedis, "a91593ee7ed135104a96853fa2a7c042"))
```

**Comment by CendioOssman** [comment] 2021-01-12 14:47
Hmm... not sure what is going wrong in that case. Can you check in the web browser what the WebSocket request looks like?

**Comment by skylar-byte** [comment] 2021-01-18 03:09
The only message I'm receiving on Chrome is `Connection closed before receiving a handshake response`

I'm using the launch.sh script but my websocket host is on another machine. I'm specifying that machine via the host and port parameters in the URL.

**Comment by CendioOssman** [comment] 2021-01-27 15:36
@pexmor, you wrote the Redia token plugin. Do you think you could help out?

**Comment by PexMor** [comment] 2021-01-30 08:47
@skylar-byte @CendioOssman sure I will check that. Hope I could reconstruct the setup.

**Comment by PexMor** [comment] 2021-01-30 10:34
It seems that the problem is two-fold, one is an extra ascii encoding which is not needed now and the second is the format of the redis response. I have made a fix and added some docs. However proper logging should be added though.

I will link the PR to this issue in a minute.

**Comment by CendioOssman** [comment] 2021-05-21 12:56
Since #475 is merged I guess this is solved.

**Closed by CendioOssman** 2021-05-21 12:56 UTC
