### ISSUE TITLE
the websokity not work well

### ISSUE THREAD

**Issue by zhangjianpinghik** [novnc/websockify#234] opened 2016-04-22 03:29 UTC
D:\share\novnc for windows\kanaka-noVNC\utils>.\old_websockify\websockify.exe --
web=.. --target-config=.\vnc_tokens\noVNCConfig.ini 8903
WARNING: no 'resource' module, daemonizing is disabled
WebSocket server settings:
- Listen on :8903
- Flash security policy server
- Web server. Web root: D:\share\novnc for windows\kanaka-noVNC
- No SSL/TLS support (no cert file)
- proxying from :8903 to targets in D:\share\novnc for windows\kanaka-noVNC\ut
  ils\vnc_tokens\noVNCConfig.ini
  handler exception: [Errno 10054]
  handler exception: [Errno 10053]
  handler exception: [Errno 10054]
  handler exception: [Errno 10054]
  handler exception: [Errno 10053]
  10.8.8.20 - - [22/Apr/2016 10:59:01] 10.8.8.20: Plain non-SSL (ws://) WebSocket
  connection
  10.8.8.20 - - [22/Apr/2016 11:04:15] 10.8.8.20: Version hybi-13, base64: 'False'

10.8.8.20 - - [22/Apr/2016 11:04:15] 10.8.8.20: Path: '/websockify/?token=host3'

10.8.8.20 - - [22/Apr/2016 11:04:15] connecting to: 10.6.21.20:5901
handler exception: [Errno 10053]
10.8.8.20: ignoring empty handshake
10.8.8.20: ignoring empty handshake
10.8.8.20: ignoring empty handshake
10.8.8.20: ignoring empty handshake
10.8.8.20: ignoring empty handshake
10.8.8.20: ignoring empty handshake
10.8.8.20 - - [22/Apr/2016 11:13:50] 10.8.8.20: Plain non-SSL (ws://) WebSocket
connection
10.8.8.20 - - [22/Apr/2016 11:13:50] 10.8.8.20: Version hybi-13, base64: 'False'

10.8.8.20 - - [22/Apr/2016 11:13:50] 10.8.8.20: Path: '/websockify/?token=host1'

10.8.8.20 - - [22/Apr/2016 11:13:50] connecting to: 10.6.21.69:5900
handler exception: [Errno 10053]
10.6.21.143 - - [22/Apr/2016 11:13:50] 10.6.21.143: Plain non-SSL (ws://) WebSoc
ket connection
10.6.21.143 - - [22/Apr/2016 11:13:50] 10.6.21.143: Version hybi-13, base64: 'Fa
lse'
10.6.21.143 - - [22/Apr/2016 11:13:50] 10.6.21.143: Path: '/websockify/?token=ho
st1'
10.6.21.143 - - [22/Apr/2016 11:13:50] connecting to: 10.6.21.69:5900
10.8.8.20 - - [22/Apr/2016 11:20:04] code 404, message File not found
handler exception: [Errno 10054]
handler exception: [Errno 10054]
handler exception: [Errno 10053]
handler exception: [Errno 10054]

**Comment by zhangjianpinghik** [comment] 2016-04-22 03:33
D:\share\novnc for windows\kanaka-noVNC\utils>.\old_websockify\websockify.exe --
web=.. --target-config=.\vnc_tokens\noVNCConfig.ini 8903

WARNING: no 'resource' module, daemonizing is disabled
WebSocket server settings:
  - Listen on :8903
  - Flash security policy server
  - Web server. Web root: D:\share\novnc for windows\kanaka-noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :8903 to targets in D:\share\novnc for windows\kanaka-noVNC\ut
ils\vnc_tokens\noVNCConfig.ini
handler exception: [Errno 10054]
handler exception: [Errno 10053]
handler exception: [Errno 10054]
handler exception: [Errno 10054]
handler exception: [Errno 10053]
10.8.8.20 - - [22/Apr/2016 10:59:01] 10.8.8.20: Plain non-SSL (ws://) WebSocket
connection
10.8.8.20 - - [22/Apr/2016 11:04:15] 10.8.8.20: Version hybi-13, base64: 'False'

10.8.8.20 - - [22/Apr/2016 11:04:15] 10.8.8.20: Path: '/websockify/?token=host3'

10.8.8.20 - - [22/Apr/2016 11:04:15] connecting to: 10.6.21.20:5901
handler exception: [Errno 10053]
10.8.8.20: ignoring empty handshake
10.8.8.20: ignoring empty handshake
10.8.8.20: ignoring empty handshake
10.8.8.20: ignoring empty handshake
10.8.8.20: ignoring empty handshake
10.8.8.20: ignoring empty handshake
10.8.8.20 - - [22/Apr/2016 11:13:50] 10.8.8.20: Plain non-SSL (ws://) WebSocket
connection
10.8.8.20 - - [22/Apr/2016 11:13:50] 10.8.8.20: Version hybi-13, base64: 'False'

10.8.8.20 - - [22/Apr/2016 11:13:50] 10.8.8.20: Path: '/websockify/?token=host1'

10.8.8.20 - - [22/Apr/2016 11:13:50] connecting to: 10.6.21.69:5900
handler exception: [Errno 10053]
10.6.21.143 - - [22/Apr/2016 11:13:50] 10.6.21.143: Plain non-SSL (ws://) WebSoc
ket connection
10.6.21.143 - - [22/Apr/2016 11:13:50] 10.6.21.143: Version hybi-13, base64: 'Fa
lse'
10.6.21.143 - - [22/Apr/2016 11:13:50] 10.6.21.143: Path: '/websockify/?token=ho
st1'
10.6.21.143 - - [22/Apr/2016 11:13:50] connecting to: 10.6.21.69:5900
10.8.8.20 - - [22/Apr/2016 11:20:04] code 404, message File not found
handler exception: [Errno 10054]
handler exception: [Errno 10054]
handler exception: [Errno 10053]
handler exception: [Errno 10054]

**Comment by DirectXMan12** [comment] 2016-06-30 20:55
This is probably a duplicate of the other windows bugs.

**Comment by CendioOssman** [comment] 2018-11-07 11:21
Yea. Closing as duplicate of #67.

**Closed by CendioOssman** 2018-11-07 11:21 UTC
Labels: Windows, bug, python
