### ISSUE TITLE
HTTPS ERROR 13 with novnc snap

### ISSUE THREAD

**Issue by ayoub-tl** [novnc/websockify#502] opened 2021-12-22 12:21 UTC
ERROR 13 when accessing with https
![image](https://user-images.githubusercontent.com/68382823/147092006-8e1cb424-dc5a-480c-b447-7aec93e6652c.png)

**Comment by CendioOssman** [comment] 2021-12-22 12:25
Are you running websockify in some restricted way? E.g. some container?

Does the ubuntu user have permission to read the certificate and key?

**Comment by ayoub-tl** [comment] 2021-12-22 12:33
yes the ubuntu user has permission 
![image](https://user-images.githubusercontent.com/68382823/147093051-931b4cbd-a0e0-46eb-a1ef-360c3844fb0e.png)
websockify is running normal , i cant even access the webpage, it works fine with HTTP

**Comment by CendioOssman** [comment] 2021-12-22 12:59
I see that it is a snap. I wonder if snaps are restricted from accessing those files... I'm afraid I'm not familiar with the restrictions snap puts in place.

The fact that it works over HTTP but not HTTPS suggests that the issue is with the certificate or key.

**Comment by CendioOssman** [comment] 2021-12-29 09:56
@tkedwards, do you have any insight? Can snaps access files like this?

**Comment by tkedwards** [comment] 2022-01-01 03:57
The Snap doesn't explicitly request the 'home' interface (which would let it access files/directories in the user's home dir): https://snapcraft.io/docs/home-interface

But from what I understand of Canonical's docs the home interface should be available automatically, unless you're using something like Ubuntu Core. Can you confirm whether you're using Ubuntu Core, or what Ubuntu version you're using?

And does connecting the home interface explicitly like this help at all?

`snap connect novnc:home :home`

**Comment by scarolan** [comment] 2022-01-26 21:24
I am having the exact same issue on Ubuntu 20.04.3 LTS.  Attempted to run the command both as the ubuntu user and as the root user, same Error 13

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```

```
root@ubuntu:~# novnc --listen 8443 --cert self.crt --key self.key --vnc ubuntu.example.com:5901
Using installed websockify at /snap/novnc/8/bin/websockify
Starting webserver and WebSockets proxy on port 8443
WebSocket server settings:
  - Listen on :8443
  - Web server. Web root: /snap/novnc/8
  - SSL/TLS support
  - proxying from :8443 to ubuntu.opnvbzn1yyhi.instruqt.io:5901

Navigate to this URL:

    http://ubuntu:8443/vnc.html?host=ubuntu&port=8443

Press Ctrl-C to exit

handler exception: [Errno 13] Permission denied
```

I replaced our public hostname above with `ubuntu.example.com`.

novnc works fine without the SSL though.

**Comment by scarolan** [comment] 2022-01-26 22:04
It appears the snap is indeed built in such a way that it can't read /home/user/self.crt and /home/user/self.key.  I tried using the tarball instead of the snap store version of novnc and it works fine.

**Comment by tkedwards** [comment] 2022-01-28 02:51
Yes, that's right the novnc snap doesn't have access to files in your home directory. I didn't add the 'home' Snap plug (allowing access to home directory) as I didn't think it was needed. I wanted to keep the interfaces it uses to a minimum for security reasons - some people would ask why does a system service like novnc need access to your $HOME?

As an alternative, if you have cert files you can put them in the Snap's user-level directories, which is /home/user/snap/novnc/current/. So your command would become:

`novnc --listen 8443 --cert ~/snap/novnc/current/self.crt --key ~/snap/novnc/current/self.key --vnc ubuntu.example.com:5901`

Does that work for you? 

@CendioOssman  we might need to update the documentation to say this

**Comment by CendioOssman** [comment] 2022-01-28 08:56
Sounds good. Just send a PR and I'll get it merged.

**Comment by CendioOssman** [comment] 2022-03-04 15:33
Fix is merged.

**Closed by CendioOssman** 2022-03-04 15:33 UTC
