### ISSUE TITLE
Google Chrome Ver 80 tagging wss:// connection as mixed content??

### ISSUE THREAD

**Issue by jeffforbes** [novnc/websockify#422] opened 2020-02-07 16:18 UTC
Our https:// protected webpage calls novnc through wss:// via websockify and it worked with chrome and firefox until the latest chrome release.  Now Chrome has trouble with the SSL certificate for the wss:// connection. The same SSl cert and key is used by apache and websocify.
Now with chrome, websockify throws this error in its log:
2020-02-07 10:40:17,506 handler exception: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:852)
2020-02-07 10:40:17,507 exception
Traceback (most recent call last):
  File "/opt/websockify/websocket.py", line 925, in top_new_client
    client = self.do_handshake(startsock, address)
  File "/opt/websockify/websocket.py", line 836, in do_handshake
    keyfile=self.key)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 1158, in wrap_socket
    ciphers=ciphers)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:852)

The javascript console in chrome shows:
vodwsclien.js:90 WebSocket connection to 'wss://nacon.com:8080/?token=status' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

I am at a loss why this is now breaking only on Chrome.
Please advise.

**Comment by CendioOssman** [comment] 2020-02-27 13:48
I'm afraid I'm unable to reproduce this issue on Linux and Windows. Is your Chrome perhaps configured in some special way? And have you verified that websockify is indeed using the same certificate?

**Comment by jeffforbes** [comment] 2020-03-03 15:00
We think that this issue was a result of Google releasing a broken version of Chrome for Linux.
The issue went away with an update.

**Comment by samhed** [comment] 2020-03-03 20:46
Closing for now then.

**Closed by samhed** 2020-03-03 20:46 UTC
