### ISSUE TITLE
Mixing Windows and Python 3.3

### ISSUE THREAD

**Issue by jmcintyre** [novnc/websockify#66] opened 2012-10-31 20:30 UTC
I have had websockify running on Windows against Python 3.2 for some time now. I've begun testing against Python 3.3 and have run into an issue. When a websocket connection is made, I receive the following error:

self = load(from_parent)
"Python\lib\multiprocessing\forking.py", line 344, in main
File "<string>", line 1, in <module>

Has anyone else tried running against Python 3.3 in Windows?

**Comment by CendioOssman** [comment] 2018-11-07 11:22
This is a duplicate of #67, where multiprocessing and Windows don't mix well.

**Closed by CendioOssman** 2018-11-07 11:22 UTC
Labels: Windows, bug, patchwelcome, python
