### ISSUE TITLE
launch.sh --vnc loaclhost:5900 can't work will in windows

### ISSUE THREAD

**Issue by xiaohuoni** [novnc/websockify#261] opened 2017-01-12 02:59 UTC
in windows run in cmd :launch.sh --vnc loaclhost:5900
log like that:
Warning: could not find self.pem
Using local websockify at /d/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
WebSocket server settings:
  - Listen on :6080
  - Flash securitypolicy server
  - Web server. Web root: D:\noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5900
WARNING: no 'numpy' module, HyBi protocol will be slower
WARNING: no 'resource' module, daemonizing is disabled
Traceback (most recent call last):
  File "D:/noVNC/utils/websockify/run", line 5, in <module>
    websockify.websocketproxy.websockify_init()
  File "D:\noVNC\utils\websockify\websockify\websocketproxy.py", line 535, in websockify_init
    server.start_server()
  File "D:\noVNC\utils\websockify\websockify\websocket.py", line 989, in start_server
    signal.SIGCHLD: signal.getsignal(signal.SIGCHLD),
AttributeError: 'module' object has no attribute 'SIGCHLD'

----------0..0---------------------------------0..0-----------------------------0..0-------------
help!!!!!!!

**Comment by CendioOssman** [comment] 2017-02-07 14:48
Duplicate of #108.

**Closed by CendioOssman** 2017-02-07 14:48 UTC
